### ISSUE TITLE
Permissions Error in Docker

### ISSUE THREAD

**Issue by meatballs** [anvil-works/anvil-runtime#22]
When using the [dockerfile](https://github.com/anvil-works/anvil-runtime/blob/master/packaging/app-server/Dockerfile) from this repo, I get a permissions error when the container starts (as it attempts to download the App Server JAR).

During the build, the JAR downloaded successfully.

```
Downloading Anvil App Server JAR to package directory
Failed to download App Server to package directory. Retrying in ~/.anvil
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/anvil_app_server/__init__.py", line 167, in find_or_download_app_server
    _urlretrieve(url, package_dir_path, show_progress)
  File "/usr/local/lib/python3.8/urllib/request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/anvil_app_server/anvil-app-server.20200515-134353.jar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/anvil-app-server", line 8, in <module>
    sys.exit(launch())
  File "/usr/local/lib/python3.8/site-packages/anvil_app_server/__init__.py", line 12, in launch
    jar_path = find_or_download_app_server()
  File "/usr/local/lib/python3.8/site-packages/anvil_app_server/__init__.py", line 172, in find_or_download_app_server
    _urlretrieve(url, home_dir_path, show_progress)
  File "/usr/local/lib/python3.8/urllib/request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/anvil/.anvil/anvil-app-server.20200515-134353.jar'
```

**Comment by clark-b124** [comment]
How did you solve this? I'm having the same problem
