### ISSUE TITLE
Error if certificates are not installed on MacOS ("SSL: CERTIFICATE_VERIFY_FAILED")

### ISSUE THREAD

**Issue by gjerman** [anvil-works/anvil-runtime#31]
Trying the minimal example fails with the following error
Any guidance on this?

```
pip install anvil-app-server
create-anvil-app todo-list MyTodoList
anvil-app-server --app MyTodoList

```

Error:

```
(venv) user@machine:~/projects/anvil-server$ anvil-app-server
Downloading Anvil App Server JAR to package directory
Failed to download App Server to package directory. Retrying in ~/.anvil
Traceback (most recent call last):
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/z/datalake/virtual_envs/20201117T185046/Ubuntu18.04/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

```

**Comment by meredydd** [comment]
Hi there,

It looks like your machine is failing to connect to Amazon S3 to download the app server JAR. It's possible your machine has outdated SSL root certificates: Amazon is [changing their TLS root chain](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/), so older machines may have trouble downloading. That link should have some tips for updating your root store!

**Comment by alexpirine** [comment]
If you're using macOS, you need to install root certificates first:

Open your Terminal, and run:

```shell
/Applications/Python\ 3.7/Install\ Certificates.command
```

This could be added to the README, as it's quite common on macOS.

Also, using the `requests` library instead of `urllib` in __init__.py would also solve the issue, since `requests` already comes with a bundle of root certificates.

https://github.com/anvil-works/anvil-runtime/blob/2755bbd1ed65d63bc183c49e70a809b8f8e708e5/packaging/app-server/anvil_app_server/__init__.py#L8

**Comment by snwight** [comment]
this is a message from the future saying, thank you kind ancestors
