### ISSUE TITLE
Error while working with example

### ISSUE THREAD

**Issue by yongalee** [anvil-works/anvil-runtime#4]
I got an error when I use 
anvil-app-server --app <my app>

The error message complains about postgres binaries
and I don't see any documentation regarding this error message.

(anvil) D:\anvil-runtime>anvil-app-server --app Classic_3
Found Anvil App Server JAR in package directory
ERROR - #error {
 :cause Missing postgres binaries
 :via
 [{:type java.lang.IllegalStateException
   :message Missing postgres binaries
   :at [io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver getPgBinary DefaultPostgresBinaryResolver.java 68]}]
 :trace
 [[io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver getPgBinary DefaultPostgresBinaryResolver.java 68]
  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres prepareBinaries EmbeddedPostgres.java 767]
  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres <init> EmbeddedPostgres.java 130]
  [io.zonky.test.db.postgres.embedded.EmbeddedPostgres$Builder start EmbeddedPostgres.java 584]
  [anvil.app_server.postgres$launch_bundled_db_BANG_ invokeStatic postgres.clj 70]
  [anvil.app_server.postgres$launch_bundled_db_BANG_ invoke postgres.clj 20]
  [anvil.app_server.run$_main$fn__1692 invoke run.clj 373]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invokeStatic core.clj 659]
  [clojure.core$update_in$up__6562 invoke core.clj 6105]
  [clojure.core$update_in invokeStatic core.clj 6106]
  [clojure.core$update_in doInvoke core.clj 6092]
  [clojure.lang.RestFn invoke RestFn.java 445]
  [anvil.app_server.run$_main invokeStatic run.clj 373]
  [anvil.app_server.run$_main doInvoke run.clj 220]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [anvil.app_server.run main nil -1]]}

**Comment by daviesian** [comment]
We include postgres binaries for most common systems, but there are bound to be some we haven't tried. It looks like you're on Windows, in which case any 64-bit version of the OS should be supported - what exact version are you using?

**Comment by yongalee** [comment]
like you mentioned i'm using windows 10
so, using linux is more secure ? in terms of unexpected errors?

**Comment by meredydd** [comment]
Hi @yongalee,

Version 1.1 (released on Friday) has better debug information for this error. Can you try it again, on the computer that caused the problem, and update us with the output?

**Comment by Samsonkin** [comment]
@meredydd Hello, sorry to bother you. I searched for the problem and only found this page. Can you tell me the possible cause of the problem?

I have the dependencies:
```
[INFO] +- io.zonky.test:embedded-database-spring-test:jar:1.5.0:compile
[INFO] |  +- io.zonky.test:embedded-database-spring-test-autoconfigure:jar:1.5.0:compile
[INFO] |  +- io.zonky.test:embedded-postgres:jar:1.2.3:compile
[INFO] |  |  +- io.zonky.test.postgres:embedded-postgres-binaries-windows-amd64:jar:11.2.0:runtime
[INFO] |  |  +- io.zonky.test.postgres:embedded-postgres-binaries-darwin-amd64:jar:11.2.0:runtime
[INFO] |  |  +- io.zonky.test.postgres:embedded-postgres-binaries-linux-amd64-alpine:jar:11.2.0:runtime
```
after changing my computer I started having problems
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.zonky.test.db.postgres.embedded.EmbeddedPostgres]: Factory method 'embeddedPostgres' threw exception; nested exception is java.lang.IllegalStateException: Missing postgres binaries
Caused by: java.lang.IllegalStateException: Missing postgres binaries
```
PC:
```
Windows 10 Pro
AMD Ryzen 7 PRO 3700
```

Thanks for your attention!

**Comment by Samsonkin** [comment]
Hello, I met a similar problem. This happened after changing the computer and setting up a clean Windows for development.

dependencies
```
[INFO] +- io.zonky.test:embedded-database-spring-test:jar:1.5.0:compile
[INFO] |  +- io.zonky.test:embedded-database-spring-test-autoconfigure:jar:1.5.0:compile
[INFO] |  +- io.zonky.test:embedded-postgres:jar:1.2.3:compile
[INFO] |  |  +- io.zonky.test.postgres:embedded-postgres-binaries-windows-amd64:jar:11.2.0:runtime
[INFO] |  |  +- io.zonky.test.postgres:embedded-postgres-binaries-darwin-amd64:jar:11.2.0:runtime
[INFO] |  |  +- io.zonky.test.postgres:embedded-postgres-binaries-linux-amd64-alpine:jar:11.2.0:runtime
```
stack trace
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedPostgres' defined in class path resource [com/netcracker/cloud/bss/cim/core/util/test/EmbeddedPostgresTestConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.zonky.test.db.postgres.embedded.EmbeddedPostgres]: Factory method 'embeddedPostgres' threw exception; nested exception is java.lang.IllegalStateException: Missing postgres binaries
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.zonky.test.db.postgres.embedded.EmbeddedPostgres]: Factory method 'embeddedPostgres' threw exception; nested exception is java.lang.IllegalStateException: Missing postgres binaries
...
Caused by: java.lang.IllegalStateException: Missing postgres binaries
	at io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver.getPgBinary(DefaultPostgresBinaryResolver.java:68)
	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.prepareBinaries(EmbeddedPostgres.java:760)
	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.<init>(EmbeddedPostgres.java:130)
	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres$Builder.start(EmbeddedPostgres.java:577)
```
Config PC:
```
Windows 10 Pro
AMD Ryzen 7 PRO 3700
```
I'm a little confused because I don't know where to look for the problem.
I tried to install PostgreSQL from www.postgresql.org 11 and 12 versions. (for a long time in one version of EmbeddedPostgres I met a problem which was solved doing this)
I tried to install visual c++ redistributable 2005 2010 2013 2015-2019 versions. (I found these tips on the Internet)
And I tried to execute for git bash
```
export LC_CTYPE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```
I think I'm missing something simple. It's driving me crazy)

**Comment by meredydd** [comment]
Closed for lack of follow-up information
