### ISSUE TITLE
Unable to use custom SMTP server

### ISSUE THREAD

**Issue by axiomsofchoice** [anvil-works/anvil-runtime#7]
In order to sign up a new user a verification needs to be sent. For QA testing we're using a local fake SMTP but the Anvil runtime cannot connect to is. This is possibly a duplicate of #6  Below were the steps I took to reproduce it:

- Create "`New Blank App`" and add the `Users` service and in `__init__` of `From1` add:

```
user = anvil.users.login_with_form()
```

- [Clone the repo](https://github.com/anvil-works/anvil-runtime/blob/master/doc/getting-started.md#clone-your-app-with-git) to a local machine

- Install [`fake-smtp-server`](https://www.npmjs.com/package/fake-smtp-server) via `npm` and start it on port `1025`.

- Download [anvil-app-server](https://github.com/anvil-works/anvil-runtime/blob/master/doc/getting-started.md) and run local instance of app using:

```
 anvil-app-server --smtp-host localhost --smtp-port 1025 --smtp-username foo --smtp-password bar
```

- Attempt to sign up as a new user.

- Observe following stack trace:

```
Found Anvil App Server JAR in package directory
Database is uninitialised. Setting up Anvil database from scratch...
Setup complete.
[INFO  anvil.core.server] HTTP Server running on port 3030
[INFO  anvil.app-server.run] App URL:  http://localhost:3030
[INFO  anvil.app-server.dispatch] Launching built-in downlink...
Warning: PDF Rendering not supported on Windows. Renderer not initialised
Connecting to ws://localhost:3030/_/downlink
Anvil websocket open
[INFO  anvil.executors.downlink] Downlink client connected with spec {:runtime "python3-full", :session_id "7RgfxJjQzjJkOxSAp3tL"}
Downlink authenticated OK
[INFO  anvil.app-server.run] SMTP Server running on port 25
[TRACE anvil.runtime.util] Creating new session pozbv5av4ekact4z3anaibls for app Example_User_Login replacing NONE (new session)
[DEBUG anvil.runtime.server] Serving app Example_User_Login
[INFO  anvil.app-server.run] [LOG :new-session] {:type browser}
[TRACE anvil.runtime.util] Using existing session pozbv5av4ekact4z3anaibls (last accessed 1589380502355, app id Example_User_Login)
[TRACE anvil.runtime.util] Using existing session pozbv5av4ekact4z3anaibls (last accessed 1589380503502, app id Example_User_Login)
[DEBUG anvil.runtime.server] Couldn't load app nil
[TRACE anvil.runtime.util] Creating new session 3bilz7jfp4ejq3pbbvnhevyx for app Example_User_Login replacing NONE (new session)
[DEBUG anvil.dispatcher.core] Dispatch! anvil.private.users.get_current_user for Example_User_Login
[DEBUG anvil.dispatcher.core] Dispatch! anvil.private.users.get_last_login_email for Example_User_Login
[DEBUG anvil.dispatcher.core] Dispatch! anvil.private.users.signup_with_email for Example_User_Login
[INFO  anvil.runtime.tables.rpc] Loading table rows (3 ms)
[INFO  anvil.runtime.tables.rpc] Loading table rows (1 ms)
[DEBUG anvil.app-server.run] [SERVER] Automatically creating column "signed_up" (datetime)
[DEBUG anvil.app-server.run] [SERVER] Automatically creating column "password_hash" (string)
[DEBUG anvil.app-server.run] [SERVER] Automatically creating column "confirmed_email" (bool)
[DEBUG anvil.app-server.run] [SERVER] Automatically creating column "email_confirmation_key" (string)
[ERROR anvil.dispatcher.native-rpc-handlers.util] Internal server error: b22f691f8b3e
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
        at anvil.dispatcher.native_rpc_handlers.email$smtp_send.invokeStatic(email.clj:291)
        at anvil.dispatcher.native_rpc_handlers.email$smtp_send.invoke(email.clj:227)
        at anvil.dispatcher.native_rpc_handlers.email$send_BANG_.invokeStatic(email.clj:164)
        at anvil.dispatcher.native_rpc_handlers.email$send_BANG_.invoke(email.clj:78)
        at anvil.dispatcher.native_rpc_handlers.users.core$send_email_BANG_.invokeStatic(core.clj:237)
        at anvil.dispatcher.native_rpc_handlers.users.core$send_email_BANG_.invoke(core.clj:232)
        at anvil.dispatcher.native_rpc_handlers.users.core$signup_with_email.invokeStatic(core.clj:261)
        at anvil.dispatcher.native_rpc_handlers.users.core$signup_with_email.invoke(core.clj:245)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at anvil.dispatcher.native_rpc_handlers.util$wrap_native_fn$fn__12201$fn__12204$fn__12213.invoke(util.clj:79)
        at anvil.dispatcher.native_rpc_handlers.util$wrap_native_fn$fn__12201$fn__12204.invoke(util.clj:78)
        at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[ERROR anvil.app-server.run] Error report from client code:
InternalError: Internal server error: b22f691f8b3e
Traceback:
  anvil-services/anvil/users.py:307

  anvil-services/anvil/users.py:307

  anvil-services/anvil/users.py:477

  anvil-services/anvil/users.py:477

  app/Example_User_Login/Form1/__init__.py:17

```
The code that produces this error is here: https://github.com/anvil-works/anvil-runtime/blob/master/server/core/src/anvil/dispatcher/native_rpc_handlers/email.clj#L291

This appears to be an issue with the [Java Mail Api](https://javaee.github.io/javamail/docs/api/index.html?javax/mail/Session.html).

**Comment by meredydd** [comment]
Oh, that's a good catch! Looks like we're not converting the port from string to number when it's read in from the command line.

**Comment by axiomsofchoice** [comment]
Many thanks for this! Just to confirm the details of the workaround. I created a file `smtp.yaml` containing:

```
smtp-host: "localhost"
smtp-port: 1025
```

Then ran the server using the following command line:

    anvil-app-server --config-file smtp.yaml

This resulted in the registration email being sent to my fake SMTP server.

**Comment by ariannedee** [comment]
I am also using `fake-smtp-server` and the same `smtp.yaml` config as above. It was working last week, but this week I'm getting the following Java error:

```
[DEBUG anvil.dispatcher.core] Dispatch! anvil.private.http.url_encode for ...
[DEBUG anvil.app-server.run] [SERVER] sending email
[DEBUG anvil.dispatcher.core] Dispatch! anvil.private.email.send.v2 for ...
[ERROR anvil.dispatcher.native-rpc-handlers.util] Internal server error: 448fcfadf796
java.lang.UnsupportedOperationException
        at anvil.dispatcher.native_rpc_handlers.email$fn__3072$get_reroute_address__3073.invoke(email.clj:24)
        at anvil.dispatcher.native_rpc_handlers.email$send_BANG_$fn__3125.invoke(email.clj:145)
        at clojure.lang.Delay.deref(Delay.java:42)
        at clojure.core$deref.invokeStatic(core.clj:2312)
        at clojure.core$deref.invoke(core.clj:2298)
        at anvil.dispatcher.native_rpc_handlers.email$send_BANG_.invokeStatic(email.clj:147)
        at anvil.dispatcher.native_rpc_handlers.email$send_BANG_.invoke(email.clj:78)
        at anvil.dispatcher.native_rpc_handlers.email$wrapped_send$fn__3226.invoke(email.clj:209)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at anvil.dispatcher.native_rpc_handlers.util$wrap_native_fn$fn__1698$fn__1701$fn__1710.invoke(util.clj:79)
        at anvil.dispatcher.native_rpc_handlers.util$wrap_native_fn$fn__1698$fn__1701.invoke(util.clj:78)
        at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
Worker terminated for IDs set() (return code -15)
[ERROR anvil.app-server.run] Error report from client code:
InternalError: Internal server error: 448fcfadf796
Traceback:
  /venv/lib/python3.8/site-packages/anvil_downlink_worker/anvil/_threaded_server.py:393
  /venv/lib/python3.8/site-packages/anvil_downlink_worker/anvil/server.py:38
  /venv/lib/python3.8/site-packages/anvil_downlink_worker/anvil/email.py:21
  App/Collaboration.py:74
  App/SecurityManagement.py:24
  app/App/Utilities/Collaborators/__init__.py:40
```

Maybe related, but I'm also getting this new warning when I try to run `anvil-app-server`

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/Users/ariannedee/.local/share/virtualenvs/App-dq062F3P/lib/python3.8/site-packages/anvil_app_server/anvil-app-server.20200515-134353.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
```
