### ISSUE TITLE
Upgrading to v1.11.0 causes "class anvil.core.ring.util$wrap_async$inner_handler$reify__5647 is not understandable"

### ISSUE THREAD

**Issue by amrael** [anvil-works/anvil-runtime#84]
We have updated our anvil server from version 1.8.0 to version 1.11.0, however, we are ceaselessly encountering the error as detailed below.

### Error log

```
May 13, 2024 at 11:34 (UTC+7:00)	[ERROR anvil.util] Reporting uncaught exception in GET /_/api/health-check	
May 13, 2024 at 11:34 (UTC+7:00)	at clojure.lang.AFn.run(AFn.java:22)	
May 13, 2024 at 11:34 (UTC+7:00)	at java.base/java.lang.Thread.run(Thread.java:1583)	
May 13, 2024 at 11:34 (UTC+7:00)	at anvil.core.worker_pool$launch_thread_BANG_$fn__585.invoke(worker_pool.clj:94)	
May 13, 2024 at 11:34 (UTC+7:00)	at anvil.core.worker_pool$run_one_task_BANG_.invoke(worker_pool.clj:38)	
May 13, 2024 at 11:34 (UTC+7:00)	at anvil.core.worker_pool$run_one_task_BANG_.invokeStatic(worker_pool.clj:55)	
May 13, 2024 at 11:34 (UTC+7:00)	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)	
May 13, 2024 at 11:34 (UTC+7:00)	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)	
May 13, 2024 at 11:34 (UTC+7:00)	at org.httpkit.server.HttpHandler.run(RingHandler.java:129)	
May 13, 2024 at 11:34 (UTC+7:00)	at org.httpkit.HttpUtils.HttpEncode(HttpUtils.java:448)	
May 13, 2024 at 11:34 (UTC+7:00)	java.lang.RuntimeException: class anvil.core.ring.util$wrap_async$inner_handler$reify__5647 is not understandable	
May 13, 2024 at 11:34 (UTC+7:00)	at org.httpkit.HttpUtils.bodyBuffer(HttpUtils.java:123)
```

### The code for the endpoint, "/_/api/health-check".

```python
@anvil.server.http_endpoint("/health-check")
def alb_health_check():
  """
  HTTP endpoint for health check.
  Returns:
    anvil.server.HttpResponse: An HTTP response indicating the status of the service.
  """
  migrations = app_tables.datamigrations.search(q.any_of(is_running=True, is_success=False))
  if len(migrations) > 0:
    return anvil.server.HttpResponse(503, "Service unavailable")

  return anvil.server.HttpResponse(200, "Request succeeded")
```

**Comment by dagginio** [comment]
Same for me. With 1.10.1 it works fine.
